name = "ModelingAndSimulation"
uuid = "5b894b6a-e612-446a-8d54-a1eeff33d94d"
authors = ["Abdulrhmn Ghanem <abdoghanem160@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
